### ISSUE TITLE
Bug: Login page text are not clearly visible in dark mode

### ISSUE THREAD

**Issue by agastya3636** [subhadipbhowmik/30-Days-Of-CPP#138]
## Add Screenshots
![image](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/124435030/7a85157b-3eda-4461-85d1-cfbeb4954df7)

**Comment by ANI2707** [comment]
@subhadipbhowmik Please assign me this issue.

**Comment by agastya3636** [comment]
@ANI2707 i please assign to me only
