### ISSUE TITLE
 [Enhancement]: Add AI Chatbot 

### ISSUE THREAD

**Issue by eiva078** [subhadipbhowmik/30-Days-Of-CPP#16]
An AI chatbot can greatly enhance the C++ education project by providing 24/7 assistance. It offers technical support for a smooth user experience. Additionally, it sends motivational messages to keep learners engaged and consistent, making the learning process more efficient and enjoyable.
I would like to work on this issue. Please assign this to me under GSSOC 24.

**Comment by subhadipbhowmik** [comment]
Sounds great. I'm eagerly looking forward to your PR.

**Comment by eiva078** [comment]
@subhadipbhowmik  Sir, the layout is already completed, and the API key is the final component needed to integrate all functionalities successfully.
Could you kindly provide the necessary API key?

**Comment by subhadipbhowmik** [comment]
> @subhadipbhowmik  Sir, the layout is already completed, and the API key is the final component needed to integrate all functionalities successfully.
> Could you kindly provide the necessary API key?

Which API Key do you need?

**Comment by eiva078** [comment]
sir, chatgpt would be good

**Comment by subhadipbhowmik** [comment]
Ok I wait till the evening.. I will share it to you.

**Comment by eiva078** [comment]
> Ok I wait till the evening.. I will share it to you.

Sir, did you get the API key yet??

**Comment by subhadipbhowmik** [comment]
Yes Brother I have created it.. How may I share it to you??

**Comment by eiva078** [comment]
> Yes Brother I have created it.. How may I share it to you??

Sir, you can mail me at eivayadav@gmail.com

**Comment by eiva078** [comment]
> Yes Brother I have created it.. How may I share it to you??
> 

Sir, I have sent you an email. Please send the API key there.

**Comment by subhadipbhowmik** [comment]
> > Yes Brother I have created it.. How may I share it to you??
> 
> Sir, I have sent you an email. Please send the API key there.

@eiva078 
I have Added The API key Named **CHAT_API_KEY** in .env file.. Now you can use it.

**Comment by eiva078** [comment]
There is an error. I have sent you an email. Please check

**Comment by subhadipbhowmik** [comment]
@eiva078 
You did a great job. It is working fine. Where did you get the API key??

**Comment by subhadipbhowmik** [comment]
Chatbot has an issue. After every 1 quetion it is replying 
Hi there 👋
How can I help you?
Rather giving proper answer about it. Could yout please fix it??

<img width="308" alt="Screenshot 2024-05-31 074744" src="https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/57017965/26ad02ae-cb33-4027-a990-a1cb9e874338">

**Comment by eiva078** [comment]
Yes sir let me check

**Comment by eiva078** [comment]
> @eiva078 You did a great job. It is working fine. Where did you get the API key??

Sir, as I don't have the ChatGPT API secret key, I need to look for an alternative method. I made this with the help of Botpress. Because it runs in a loop, I have increased the number of nodes, but after replying to three questions, the 'Hi there' text will be shown again.
