### ISSUE TITLE
Auto Commenting when a PR is merged 

### ISSUE THREAD

**Issue by suhanipaliwal** [subhadipbhowmik/30-Days-Of-CPP#21]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by subhadipbhowmik** [comment]
Hi @suhanipaliwal 

Thank you for suggesting this feature! It indeed addresses an important aspect of project management by streamlining communication and providing timely feedback to contributors. 

I'm happy to assign this issue to you under GSSOC'24. Please make sure to update us on your progress and feel free to reach out if you need any assistance or clarification. We're looking forward to your contributions!

**Comment by Anshika14528** [comment]
@subhadipbhowmik sir , their is an issue in the workflow of autocomment on pr merged 
 I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message
<img width="1454" alt="Screenshot 2024-06-05 at 1 09 44 PM" src="https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/168436423/b8d9fe5c-444c-4198-a1b3-22709beb3d0d">


I want to work on this issue can i raise an issue for that please.
