### ISSUE TITLE
Add a Better Scroll-to-top button with fixed position

### ISSUE THREAD

**Issue by MastanSayyad** [subhadipbhowmik/30-Days-Of-CPP#223]
Hey  @subhadipbhowmik It would be much better if the scroll to top button appear when scroll a little down from top and have a fixed position, implementing a scroll-to-top button can enhance user experience by providing a convenient way for users to quickly return to the top of the page.

I would like to take on this task, Could you please assign this issue to me under GSSOC'24?

## The expected behavior

- The button will only appear after the user has scrolled down a certain distance from the top of the page
- Designed as a small, round button with an arrow icon pointing upwards.
- Styling that matches the website’s overall design, with appropriate hover effects.
- When clicked, the button will smoothly scroll the user back to the top of the page.

**Comment by kashvi9** [comment]
Hey @subhadipbhowmik ,
You haven't assigned this issue yet to @MastanSayyad

**Comment by kashvi9** [comment]
> Hey @subhadipbhowmik , You haven't assigned this issue yet to @MastanSayyad

If you want, I can also work on this issue under GSSOC'24
