### ISSUE TITLE
Feature request issues template

### ISSUE THREAD

**Issue by suhanipaliwal** [subhadipbhowmik/30-Days-Of-CPP#25]
I would like to add an issues template for feature request issues in this repository. Currently this repository only has issue templates for bug fixes and content on website. I believe that having a standardised template for new feature requests will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review issues.

Could you please assign this issue to me under GSSOC'24.

**Comment by subhadipbhowmik** [comment]
We do not need this time.
