### ISSUE TITLE
Adding Heap questions in blog

### ISSUE THREAD

**Issue by Amruta7203** [subhadipbhowmik/30-Days-Of-CPP#263]
### Select the Day of Content

others

### What information is missing?

Adding questions of various difficulty levels on Heap in the Blog.

**Comment by Mooosiee** [comment]
> ### Select the Day of Content
> others
> 
> ### What information is missing?
> Adding questions of various difficulty levels on Heap in the Blog.

Hi @Amruta7203 i am also adding linked list questions how many questions are you going to add and in what structure could you help me out?

**Comment by Amruta7203** [comment]
@subhadipbhowmik Pls assign it to me
