### ISSUE TITLE
Add more content in pointers in array C++

### ISSUE THREAD

**Issue by vanisharma2003** [subhadipbhowmik/30-Days-Of-CPP#269]
### Select the Day of Content

Day 11

### What information is missing?

Add more question related to pointers in array. As pointers in array is very important so more questions should be add here for reference. More questions means people can practice more and that will enhance website a lot. People will visit website more and practice more. This will also improve ranking of the website.

**Comment by NiharikaSaxena18** [comment]
I want to work on this issue under GSSOC '24. Please assign it to me.

**Comment by vanisharma2003** [comment]
@subhadipbhowmik is this issue assigned to me ?
As label is added but I am not assigned.

**Comment by vanisharma2003** [comment]
@subhadipbhowmik my branch is merged but it does not show in leaderboard
