### ISSUE TITLE
Day -14 : C++ Standard Template Library (STL)

### ISSUE THREAD

**Issue by Samrudhi00** [subhadipbhowmik/30-Days-Of-CPP#270]
### Select the Day of Content

Day 14

### What information is missing?

**Select the Day of Content**
Day 14

**What information is missing?**
The content for reference in C++ Standard Template Library (STL)

please assign me this issue under GSSoC'24

**Comment by srilekha279** [comment]
Kindly assign this issue. I also want to contribute to this.
