### ISSUE TITLE
Automatic Comment on Issue Close

### ISSUE THREAD

**Issue by thevijayshankersharma** [subhadipbhowmik/30-Days-Of-CPP#290]
The feature I'm proposing involves automatically commenting on an issue when it is closed within the project repository. This comment will serve as a closing message, expressing gratitude to the contributor for their input, informing them of the issue's resolution status, and providing any necessary next steps or additional information.

**Comment by subhadipbhowmik** [comment]
> The feature I'm proposing involves automatically commenting on an issue when it is closed within the project repository. This comment will serve as a closing message, expressing gratitude to the contributor for their input, informing them of the issue's resolution status, and providing any necessary next steps or additional information.

These are not important. And we already have.

**Comment by subhadipbhowmik** [comment]
Our main focus on providing Insightful Content
