### ISSUE TITLE
Bug: Replace text with icons

### ISSUE THREAD

**Issue by AkhilaSunesh** [subhadipbhowmik/30-Days-Of-CPP#299]
## Add Screenshots
![image](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/140897461/577bff2a-b683-47a6-9aa1-6c207745f395)

## The current behavior
Not professional 

## The expected behavior
better outlook of the website

**Comment by yash28goyal** [comment]
Please assign this bug to me I am intereseted in resolving this bug.
