### ISSUE TITLE
Want To Add more Functions Problems

### ISSUE THREAD

**Issue by nishant0708** [subhadipbhowmik/30-Days-Of-CPP#350]
### Select the Day of Content

others

### What information is missing?

Want  to Add More Functions problem

**Comment by anshikatiwari20** [comment]
I am a GSSoC contributor and would like to work on issue #350 to add more functions problems as requested. Could you please assign this issue to me? Thank you!

**Comment by anshikatiwari20** [comment]
I am a GSSoC contributor and would like to work on issue #350 to add more functions problems as requested. Could you please assign this issue to me? Thank you!
