### ISSUE TITLE
Bug: Align Footer Content

### ISSUE THREAD

**Issue by m3kvt** [subhadipbhowmik/30-Days-Of-CPP#36]
## Describe the bug
In mobile view, the footer contents are said to be along the left margin. I would like to align it to the center to look more attractive.

## Add Screenshots
![Screenshot 2024-05-29 004040](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/b96ff9ef-c8ba-447f-a2ad-7e028005ac95)

## Steps To Reproduce

1. Go to  Homepage
2. Scroll down to Footer

## The current behavior
The footer contents are left aligned.

## The expected behavior
Footer contents are aligned center.
![image](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/045696e0-d455-4f46-8e0f-b8f53fc43cfc)

**Comment by subhadipbhowmik** [comment]
Actually It Is Built On Docusarus. So the Layout Is Designed Internally By [Meta](https://opensource.fb.com/projects/) read this documentation to change the existing design [click here](https://docusaurus.io/docs/swizzling)

**Comment by subhadipbhowmik** [comment]
> I added a css style for footer in src/css/custom.css and it works.
> Is this ok or should I do swizzling ?
> ![Screenshot 2024-05-29 102227](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/5cc4b627-9ddc-48ff-b585-ca5a344203cc)
> 

Ok if it's working fine then there is no need to swizzling. Could you please share the output for All Mobile As Well as Tab.

**Comment by subhadipbhowmik** [comment]
> > Ok if it's working fine then there is no need to swizzling. Could you please share the output for All Mobile As Well as Tab.
> 
> I've added that in the PR

Ok just wait a while.
