### ISSUE TITLE
Bug: Chatbot color should be blue.

### ISSUE THREAD

**Issue by zalabhavy** [subhadipbhowmik/30-Days-Of-CPP#414]
## Describe the bug
It is not proper visible due to over lapping of same color.

## Add Screenshots
![image](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/126322584/5db56d7c-84a9-4f68-bda6-d98e65a33db2)

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@subhadipbhowmik
