### ISSUE TITLE
Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [subhadipbhowmik/30-Days-Of-CPP#428]
A preloader is an essential feature for enhancing user experience by indicating the progress of loading content. It helps in keeping the users engaged while the main content is being fetched or rendered. Implementing a preloader can significantly improve the perceived performance of our application.

Is your feature request related to a problem? Please describe.
Yes, the absence of a preloader can lead to a poor user experience as users may not understand whether the application is working or not while content is being loaded. This can cause frustration and potentially lead to users abandoning the application. A preloader helps to keep users engaged by providing a visual indication that content is loading.

Describe the solution you'd like
**Design and Appearance:**
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

**Functionality:**
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

**Performance:**
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

**Implementation:**
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

My Previous Works:-

https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/146121869/1ce5804b-fa8b-4495-bd14-d53afdaec6d4

https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/146121869/f9719412-8948-4389-9ab6-01837666d009

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@subhadipbhowmik

**Comment by TheNikhilRaj** [comment]
@subhadipbhowmik  git clone not properly working it's giving error while cloning!
