### ISSUE TITLE
Bug: Dark mode not fully applied at all resolutions.

### ISSUE THREAD

**Issue by Jemipaul123** [subhadipbhowmik/30-Days-Of-CPP#48]
![Screenshot 2024-05-30 003226](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/107522016/f16d9d13-073a-4ee7-ab5c-e18a4b096b51)
![Screenshot 2024-05-30 003206](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/107522016/3cf94b92-9449-43fa-9e52-515fb1b1cae3)

In the first resolution dark theme is applied completely. But in the second resolution, the dark theme is applied only on half of the page.
I would like to work on this issue. I am a GSSOC'24 contributor.Pls assign me this issue. @subhadipbhowmik

**Comment by subhadipbhowmik** [comment]
Looking forward to see your PR ASAP.
