### ISSUE TITLE
Bug: Improve the responsiveness of the website

### ISSUE THREAD

**Issue by Sambit-Mondal** [subhadipbhowmik/30-Days-Of-CPP#50]
## Describe the bug

The content in the boxes on the website gets overflown on small devices (like, mobiles). This leads to a poor User Experience.

## Add Screenshots

![Screenshot 2024-05-30 094202](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/138088550/020a5501-267d-4303-938e-f0c5767b80f7)

## Steps To Reproduce

1. Go to the website.
2. Click on Inspect.
3. Adjust the width of the screen to that of mobile phones.

## The current behavior

The content in the boxes on the website gets overflown on small devices (like, mobiles).

## The expected behavior

The page should have been properly responsive, and the content should have been automatically fitted into the boxes.

**Comment by sanjanasp786** [comment]
hey could you please assign this to me under ggsoc'24
