### ISSUE TITLE
Remaking the blog page 

### ISSUE THREAD

**Issue by ayush-848** [subhadipbhowmik/30-Days-Of-CPP#528]
### Site URL

https://subhadipbhowmik.github.io/30-Days-Of-CPP/blog

### What information was incorrect, unhelpful, or incomplete?

I want to redesign the blog page like with a card like format
Onclick the user can read the full blog

### What did you expect to see?

I want to redesign the blog page like with a card like format
Onclick the user can read the full blog

**Comment by Shalinimariappan** [comment]
Can I remake this page . Please assign to me
