### ISSUE TITLE
 Its not clearly visible  ` already have an account`

### ISSUE THREAD

**Issue by Ketanop321** [subhadipbhowmik/30-Days-Of-CPP#55]
`Already have an account` in signup and login page  is not visible 

go to signup page there you can see it.

![Screenshot 2024-05-30 155726](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/146806880/bd1ca724-0d4d-43f4-8bd3-f371d978cb41)

**Comment by yash28goyal** [comment]
I want to fix this bug so please assign this to me.

**Comment by Sibam-Paul** [comment]
Please assign

**Comment by bhuvangoel04** [comment]
Please assign me this issue.

**Comment by Ketanop321** [comment]
I have completed my previous issue same day , kindly assign me this issue so i can also solve this one as early as possible @subhadipbhowmik
