### ISSUE TITLE
Community Engagement elements are outside of box

### ISSUE THREAD

**Issue by Ketanop321** [subhadipbhowmik/30-Days-Of-CPP#56]
The text written in Community Engagement box got outside of conatainer

![Screenshot 2024-05-30 160010](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/146806880/522d09bc-8ae2-4ee7-bdb7-670f470166ae)

## Steps To Reproduce

1. Go to 'home page.'
2. scroll down to Community Engagement

## The expected behavior
text should to be inside box

**Comment by subhadipbhowmik** [comment]
This issue is already is already been raised.. You can work upon it.
