### ISSUE TITLE
Add Back to Top arrow

### ISSUE THREAD

**Issue by m3kvt** [subhadipbhowmik/30-Days-Of-CPP#60]
## Describe 
I would like to add a back to top navigation in home page that helps users to navigate to the top of the home page.

## Add Screenshots
![image](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/06cd6a03-1109-44a3-bbf5-e0dfcb19b730)
![Screenshot 2024-05-30 193946](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/37c42aa1-3951-441b-b886-6c21ccb017f2)

## Steps To Reproduce

1. Go to the website
2. Scroll down to footer

**Comment by subhadipbhowmik** [comment]
> ## Describe
> I would like to add a back to top navigation in home page that helps users to navigate to the top of the home page.
> 
> ## Add Screenshots
> ![image](https://private-user-images.githubusercontent.com/98379619/335218631-06cd6a03-1109-44a3-bbf5-e0dfcb19b730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTg4MTgsIm5iZiI6MTcxNzExODUxOCwicGF0aCI6Ii85ODM3OTYxOS8zMzUyMTg2MzEtMDZjZDZhMDMtMTEwOS00NGEzLWJiZjUtZTBkZmNiMTliNzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAxMjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNGEyNTFkOWI3OTlmNjFmMjQ2NDEwN2FiNjkyM2I4MGIxYjgwYTM1NmYwZmNiZmNhMTY3MDM1YmQ3Yjg5ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BPuW_eEfPrhukcUBQ7BlsPs0aNSxfRULPLRHLnoYy-Y) ![Screenshot 2024-05-30 193946](https://private-user-images.githubusercontent.com/98379619/335219567-37c42aa1-3951-441b-b886-6c21ccb017f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTg4MTgsIm5iZiI6MTcxNzExODUxOCwicGF0aCI6Ii85ODM3OTYxOS8zMzUyMTk1NjctMzdjNDJhYTEtMzk1MS00NDFiLWI4ODYtNmMyMWNjYjAxN2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAxMjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYTVkZDc0ZWJlNzYxZjI3NjAyZjNkNjU2OTA2Mjc1ZDA0MmNlNTQwYWZlYzZlZDUzZmQxMGFmNjUxYThjMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.inHysqxm2L8pT_6dKXsfu72URGnIOob27vJFzJ5awPQ)
> 
> ## Steps To Reproduce
> 1. Go to the website
> 2. Scroll down to footer

Good idea. Actually We are integrating AI/Chatbot  in that portion too.. So plese the design part in your mind..

![335365378-29d5a14c-e8e7-4793-9530-4fd87a0b3fd7](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/57017965/39334581-82fc-4802-b34d-c88b98fa3d5c)

**Comment by m3kvt** [comment]
Is this ok


https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/f5288527-9bee-4279-b571-126effe78b59
