### ISSUE TITLE
Feature: Improving the UI of the navbar

### ISSUE THREAD

**Issue by Sibam-Paul** [subhadipbhowmik/30-Days-Of-CPP#67]
### Want to add blur background to the navbar 
![image](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/158052549/629fc81d-feb8-4bba-a911-8bc9bba47506)

_please assign me this issue under gssoc'24_

**Comment by Sibam-Paul** [comment]
@subhadipbhowmik Please assign me this issue

**Comment by subhadipbhowmik** [comment]
> @subhadipbhowmik Please assign me this issue

Looking forward to see your PR.

**Comment by Sibam-Paul** [comment]
need help in understanding the code

**Comment by Shalinimariappan** [comment]
Can I do redesign of navbar

**Comment by Sibam-Paul** [comment]
@subhadipbhowmik Sorry I will generate PR in 2 days , I was having exam . And haven't seen this issue after it due to crowded github issues
