### ISSUE TITLE
Signup/Login Page Heading Issue

### ISSUE THREAD

**Issue by udbhav26** [subhadipbhowmik/30-Days-Of-CPP#70]
At the SignUp and Login Pages the heading given as SignUp and Login respectively is not in center. As from a user's view who is using the website on PC/laptop it's very inappropriate because it ruins the basic UI of the website and thus the experience of the user.

![WhatsApp Image 2024-05-31 at 01 55 59_b043f0ba](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/149710322/466cf55d-329c-43ba-95ab-3f7286bd75f0)
![WhatsApp Image 2024-05-31 at 01 56 34_fc56422f](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/149710322/ef430290-fb36-40dc-b343-eb63a6b84801)

## Steps To Reproduce

1. Go to the html file of login and signup page
2. Click on h1 tag and add class="center" 
3. Now Go to the css file of both the login and signup pages
4. Add this code there - 
   h1.center{
       text-align: center;
       border: 3px solid green;
   }

I observed that my heading Signup and Login are now at the center in their respective pages

I expected the same behavior as i have observed in the current behavior.

**Comment by udbhav26** [comment]
@subhadipbhowmik sir please assign me this issue

**Comment by udbhav26** [comment]
@subhadipbhowmik sir please assign me this issue.

**Comment by sri766** [comment]
Hello @subhadipbhowmik  Please assign this issue. I want to contribute to it.
