### ISSUE TITLE
Login/Signup Page content not visible in dark mode

### ISSUE THREAD

**Issue by udbhav26** [subhadipbhowmik/30-Days-Of-CPP#71]
The text written on Sign Up page "Already have an account?" is not visible after the dark mode is turned on. Same issue is with Login page for the text "Don't have an account yet?".

![WhatsApp Image 2024-05-31 at 02 30 05_27d2559e](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/149710322/ae610a15-dc95-40dc-adb9-80a3e7104bab)
![Screenshot 2024-05-31 023401](https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/149710322/5e1ad922-6efe-4cc5-a623-5d0899b391ba)

## Steps To Reproduce

1. Go to html file of login/signup page
2. Click on the paragraph tag of both the text.
3. Add class="font-color" to these tags.
4. Now Go to css file of these pages add their this code snippet - 
5. p.font-color{
        color: black;
    }

The color of the texts got changed to black as i wanted and hence the text is now visible in dark mode too.

I expected the same thing to happen as i observed its current behavior.

**Comment by udbhav26** [comment]
@subhadipbhowmik sir please assign me this issue.

**Comment by sri766** [comment]
Hello @subhadipbhowmik,

This is Srisanth. Can I contribute to this issue? I have fixed the problem. I have made the changes you asked for.

Here is the screenshot of the updated page:
![Screenshot from 2024-05-31 09-57-48.png](URL_TO_UPDATED_IMG)

### Changes Made:
1. Added a CSS class `.dark-text` in `/css/custom.css`.
2. Applied the `.dark-text` class to the `<p>` tag in the HTML file.
