### ISSUE TITLE
Content Enhancement

### ISSUE THREAD

**Issue by sakshiigdtuw** [subhadipbhowmik/30-Days-Of-CPP#9]
Hello mentor, I want to change the content delivered in the original website . In both day 1 and day 2 and also each topic contain same content just with little modification in the first 2-3 lines . I want to make your project more effective and efficient by changing the content according to the given topic . 
Kindly assign me this issue.

**Comment by subhadipbhowmik** [comment]
Hi @sakshiigdtuw 

Thank you for your interest in enhancing the content of our project. We appreciate your initiative to make the material more effective and efficient for our users.

I've assigned you the issue to update the content for Day 1 and Day 2, as well as for each topic with the required modifications. Your contributions will undoubtedly improve the overall quality of our project.

Please feel free to reach out if you need any guidance or assistance along the way. We look forward to seeing the improvements you make!
