### ISSUE TITLE
Add Day 7 Content - ternary operator

### ISSUE THREAD

**Issue by Varad0014** [subhadipbhowmik/30-Days-Of-CPP#94]
### Select the Day of Content

Day 7

### What information is missing?

I would like to add information about ternary opeartors by completing the tasks mentioned in the file.

**Comment by subhadipbhowmik** [comment]
Day 07 Has 3 Content Choose any of them and then Raise PR.

**Comment by lovelymahor** [comment]
I also want to work on this issue, please assign it to me
